# Generated by Django 2.2.1 on 2019-05-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuringTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.IntegerField()),
                ('set', models.IntegerField()),
                ('is_true', models.BooleanField()),
                ('is_correct', models.BooleanField()),
                ('time', models.DurationField()),
                ('ip_address', models.CharField(max_length=128)),
            ],
        ),
    ]
